
install:
  # Check Travis CI build status, from https://gist.github.com/ndbroadbent/1708408
  - gem install hub | tail -2
  - ruby -e 'require "json"' 2>/dev/null || gem install json

script: 
  - ./do_grade
